project_name: kr8
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    main: .
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    binary: kr8
dockers:
  -
    image_templates: 
      - 'apptio/kr8:{{ .Tag }}'
      - 'apptio/kr8:latest'
    dockerfile: Dockerfile-goreleaser
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
nfpms:
  -
    vendor: Apptio TechOps
    homepage: "https://github.com/apptio/kr8"
    description: "Opinionated configuration management tool for Kubernetes Cluster"
    license: MIT
    formats:
      - rpm
      - deb
    bindir: /usr/local/bin
brews:
  -
    github:
      owner: apptio
      name: homebrew-tap

    commit_author:
      name: release
      email: release@apptio.com

    homepage: "https://kr8.rocks"
    description: "Opinionated configuration management tool for Kubernetes Cluster"
    install: |
      bin.install "kr8"
      bin.install "scripts/kr8-helpers"
    dependencies:
      - kubernetes-helm
      - jsonnet
      - go-task/tap/go-task
