language: go
addons:
  apt:
    packages:
    - rpm
services:
- docker
after_success:
- test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
install: env && go mod download
script: true
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
env:
  global:
  - GO111MODULE=on
  - secure: FTEou/Sy0i5Qxiln8nVILuJ8ceg/aCGv68/fAubU3LxgAUxg4uFJJP3t/w+Uaq8vOG4XIT/KERT4f6Jsph0X4AEvawgBMWeKYkRt0Aj7V15ASs/yAEJchpamKrktwfv5/QIN7PRrZinFAPFmYKrb8RqX6QWGZ+nNpb0dDzyp0oIis6Y1tGFEIgPS4BzbWQRlGzWYwjAbGNgNsJdmTZJy2B0/cOBEgroceBHrWFIvrodTQeVLWQD9kKcMXW36GiWJgdNsmDtHh4roQHsUX3aTHqqzTOjbBK4ENK4CJKNVV4Im1UhYMF+b5JIrfM4+EtDDahJHJJr5UQe/Ka5IPrzHIniEoWwlMkdA4xKCLvIMCZ10lo/+75dePy6wrTTiigYUPKdJOe3VJLGuf3PIoXKulnsXAHu+xaY2S+DWgOjMbuKhJMvojaP+OwkA4LFNVayJkuSQ2bY+zmWKHN5BZ/2zAZfFLEuV4Tz3wAzu+EFjUY+6rWjSKYMxw9DCKr3PGSkkMvZyzhqKTBpVkLOnCraxZXEuvMRId7oDwXhdEm5XZ+CkkxKYRV8nZV2ZNC8XS2Lw4Rjgk8SEY177lc/TP5JXjS6FO/V8R0rDceiuVW5h5yXnIHwNAMPIo2fA9aOfvrsUBqco8N1EmAofWszWwmO12LF63e3NNFBzC4BcqHl1u0I=
  - secure: foi0pmM1+/0C+fuvg9CBeWvR62F9KVtEbtA3EPdPQlhsNNir3ygkqHMEsGtpJEz3SiRdlYO2mxg3PxNoBd3k4m2cQoi82jaMPZBh1diucB1gXypAsfyOuE0GCCgT0txiky6V54ygtMzJz9/49nY47iv6Me0y6Ft5NTil79J8D37KARY8oP+HrDwADcRW0OZ0sTIA8r9r16PKIV0hBNJUK2InW6mLwM+owwt97onbaPCLhjq1Ox13SYrXdlNiVZIrqJZEG6F54nmnUXW0YCZBdMVDu/RYTDT8Qsqu4CWKLWTcAhpy9zOAfTIsWUQJkxkgchpELx1DRidpnSELWFb4jCNQ337SS/XgHgqk8fME/oendpdif2xedhIlRjHv0XALotJzGtD6HlchomDV+ytPegdl1wGO+yWvvLUViTCrZ/BjvD9KQDqy+BiMywR4G+xRQ7IWmR8Sk+tlqsl22Qm3js6irtozOg7iBk4iLj+pIhI3jrKsFwQGxkxo7XrN6tK+J1pUm4zGeVAwGyskhu5gWyTO9MT4K82paUW0tUY1WCHCQupDPX5bZlM/RPEYCgkyfjh/nTYuLOEB5nBxG+cyADvjHHmIOozMTdNXvImhal2UNETRscs+jZGBEVL8s2kY/0tmBhuZdulgjI+YowPbXLu1xdizSWFUA3tr+tRRcJ0=
  matrix:
    secure: PC1hNVtQ2wpq58KRAOfu9fnxG3Sp/Oenl5x21e0a7+/kiZQpATYYOpnsluSyk+7XwBob03TgptMIreteRgdUWn1png61SGRm2rhHwkl8z8OEHgcY46kw26CuLaruJOM8kGiAvJ9+wiuzq5sETGXXOKHOibKel5pVaIrUHAvo+xzuYmDltpoyUGRaj6iMj1n38JXuu3AVOz4X/i7MlIkoOiI19u0ezcID5xhGhmxbxgR85kfWCIPbHm+cYcZqHBs77glf9zQktvf0/CWC1bn3eyXyK4ff+GRCw19tFB+Gf1cj4w7xhAPnSLuVMNFaSJHfOo5SkyWqhPLvVwvztbWYLy9+qIyL0Sz3P3BhYOQSdk4SyjpZty324yGWDTygx1taXgTLFvq7Gp8ntXwu8KA97+SfVjUM0wpkK0rXcXKj37pF7ie8O5+pQQKUALXj7P8buNUUyyRIa8zX8LI58Jf23tLLe7VVGE12PMcaS5D4uLDPeJy/aoAIZVkpIw9Leg+fWVxUUcBPia+ENgz6sizXsTGrgiwwNPsc1UWmaVAhpK5ikhC54Py6Tyt03krD1Z8CJgg7kM8jyC3XINc8adRW5yTHsV3opv+YviInDN9EJA2uyPz/4OTpDkGznmK4XDnhZAW3/rOEFySq42CxUUHp7Cy2IfPIQNx2SPUI0ekXU7g=
